apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-db
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-db
  template:
    metadata:
      labels:
        app: todo-db
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: todo
            - name: POSTGRES_PASSWORD
              value: todo
            - name: POSTGRES_DB
              value: todo
          ports:
            - containerPort: 5432
